# Generated by Django 5.1.7 on 2025-03-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('hyderabad', 'Hyderabad'), ('odisha', 'Odisha'), ('bangalore', 'Bangalore')], max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('slot_timings', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('understanding', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('overall_feedback', models.IntegerField()),
                ('homework', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
